POST http://localhost:3000/usuario
content-type: application/json

{
    "nome": "Leonardo Leitão",
    "email": "leonardo@email.com",
    "senha": "232323"
}

###
PATCH http://localhost:3000/usuario/1
content-type: application/json

{
    "nome": "Leonardo Leitão",
    "email": "leonardo@email.com"
}

###
GET http://localhost:3000/usuario

###
GET http://localhost:3000/usuario/1

###
DELETE http://localhost:3000/usuario/2